suite_name: "CheckpointManager Benchmark"

mesh_configs:
  - mesh_axes: ["data", "model"]
    ici_parallelism: {"data": 2, "model": 2}
  - mesh_axes: ["data", "model"]
    ici_parallelism: {"data": 1, "model": 1}
    dcn_parallelism: {"data": 4, "model": 1}

checkpoint_config:
  spec:
    array: {dtype: "float32", shape: [1024, 2048], sharding: ["data", "model"]}

benchmarks:
  - generator: "orbax.checkpoint._src.testing.benchmarks.checkpoint_manager_benchmark.CheckpointManagerBenchmark"
    options:
      save_interval_steps: [1]
      max_to_keep: [1]
      train_steps: [1]
