# The name for the entire test suite run.
# Assumes v5p-256 (128 chips)
suite_name: "Llama 3.1 70B"
num_repeats: 1


mesh_config:
  mesh_axes: ["data", "fsdp", "tensor"]
  # SHould match reference_sharding_path.
  ici_parallelism: {"data": 4, "fsdp": 8, "tensor": 4}

# Note: checkpoint_config field not specified.
checkpoint_config:
  path: "gs://orbax-benchmarks/checkpoints/llama-3.1-70B-checkpoints/0/items"
  sharding_config_path: "gs://orbax-benchmarks/sharding-configs/llama3.1-70b-v5p-256-data-4-fsdp-8-tensor-4/abstract_state.json"

benchmarks:
  - generator: "orbax.checkpoint._src.testing.benchmarks.v1.benchmark.Benchmark"
    options:
      # --- Generator Options ---
      # These keys must match the attributes of the `BenchmarkOptions` class
      # associated with the `Benchmark` generator.
      async_enabled: true
      use_ocdbt: true
      use_zarr3: true
      use_replica_parallel: false
      use_compression: true
