# The name for the entire test suite run.
# Assumes v5p-64 (32 chips)
suite_name: "llama-70b_reshard_4-8-4_to_1-32-1"
num_repeats: 20


mesh_config:
  mesh_axes: ["data", "fsdp", "tensor"]
  # SHould match reference_sharding_path.
  ici_parallelism: {"data": 1, "fsdp": 32, "tensor": 1}

# Note: checkpoint_config field not specified.

benchmarks:
  - generator: "orbax.checkpoint._src.testing.benchmarks.v1.resharding_benchmark.ReshardingBenchmark"
    options:
      # --- Generator Options ---
      # These keys must match the attributes of the `ReshardingBenchmarkOptions` class
      # associated with the `ReshardingBenchmark` generator.
      async_enabled: true
      use_ocdbt: true
      use_zarr3: true
      use_replica_parallel: false
      use_compression: true
      reference_checkpoint_path: "gs://orbax-benchmarks/checkpoints/llama-70b_generate_4-8-4/ckpt"
      reference_sharding_path: "gs://orbax-benchmarks/sharding-configs/llama3.1-70b-v5p-64-data-1-fsdp-32-tensor-1/abstract_state.json"
